"""Initial MVP schema (ESD §6): incidents, agent audit trail, runbooks (pgvector),
users, and the monthly-partitioned audit log.

Hand-written rather than autogenerated because it must also (a) enable the pgvector extension,
(b) build the HNSW index for runbook similarity search (ESD §15), and (c) create ``audit_log`` as a
range-partitioned table with monthly children (ESD §17 [review fix]) — none of which Alembic
autogenerate produces.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-20
"""

from __future__ import annotations

import datetime
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# --- Enum type definitions (native Postgres enums; created once, referenced by name). ---
SEVERITY = ("P1", "P2", "P3", "P4")
INCIDENT_STATE = (
    "open",
    "investigating",
    "hypothesis_formed",
    "remediation_proposed",
    "remediation_approved",
    "remediation_executed",
    "monitoring",
    "resolved",
    "closed",
    "reopened",
)
ACTOR_TYPE = ("agent", "human", "system")
ALERT_SOURCE = ("prometheus", "github", "pagerduty")
EVIDENCE_TYPE = ("log", "metric", "diff")
AGENT_MESSAGE_TYPE = ("reasoning", "action", "handoff")
USER_ROLE = ("admin", "on_call_engineer", "viewer")
RUNBOOK_SOURCE = ("internal", "postmortem_corpus")

_ENUMS = {
    "severity": SEVERITY,
    "incident_state": INCIDENT_STATE,
    "actor_type": ACTOR_TYPE,
    "alert_source": ALERT_SOURCE,
    "evidence_type": EVIDENCE_TYPE,
    "agent_message_type": AGENT_MESSAGE_TYPE,
    "user_role": USER_ROLE,
    "runbook_source": RUNBOOK_SOURCE,
}

# Retention window for audit_log partitions (ESD §17: 13-month rolling).
_PARTITION_MONTHS = 13
_PARTITION_START = datetime.date(2026, 7, 1)


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created native enum by name (no CREATE TYPE emitted)."""
    return postgresql.ENUM(*_ENUMS[name], name=name, create_type=False)


def _first_of_next_month(d: datetime.date) -> datetime.date:
    return datetime.date(d.year + (d.month // 12), (d.month % 12) + 1, 1)


def upgrade() -> None:
    bind = op.get_bind()

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    for name, values in _ENUMS.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    # --- incidents ---
    op.create_table(
        "incidents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("external_alert_id", sa.String(), nullable=False),
        sa.Column("alert_source", _enum("alert_source"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("severity", _enum("severity"), nullable=False),
        sa.Column("state", _enum("incident_state"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint(
            "alert_source", "external_alert_id", name="uq_incidents_source_external_id"
        ),
    )
    op.create_index("ix_incidents_service_name", "incidents", ["service_name"])
    op.create_index("ix_incidents_state", "incidents", ["state"])

    # --- incident_state_transitions ---
    op.create_table(
        "incident_state_transitions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("from_state", _enum("incident_state"), nullable=False),
        sa.Column("to_state", _enum("incident_state"), nullable=False),
        sa.Column("actor_type", _enum("actor_type"), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_incident_state_transitions_incident_id",
        "incident_state_transitions",
        ["incident_id"],
    )

    # --- agent_steps ---
    op.create_table(
        "agent_steps",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("ensemble_pass_index", sa.Integer(), nullable=True),
        sa.Column("input_summary", sa.Text(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("structured_output", postgresql.JSONB(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_agent_steps_incident_id", "agent_steps", ["incident_id"])

    # --- agent_messages ---
    op.create_table(
        "agent_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("message_type", _enum("agent_message_type"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_agent_messages_incident_id", "agent_messages", ["incident_id"])

    # --- evidence_citations ---
    op.create_table(
        "evidence_citations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("agent_step_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("evidence_type", _enum("evidence_type"), nullable=False),
        sa.Column("evidence_ref", sa.String(), nullable=False),
        sa.Column("evidence_snippet_redacted", sa.Text(), nullable=True),
        sa.Column("validated_by_observer", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.ForeignKeyConstraint(["agent_step_id"], ["agent_steps.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_evidence_citations_agent_step_id", "evidence_citations", ["agent_step_id"])

    # --- runbooks (pgvector) ---
    op.create_table(
        "runbooks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("source", _enum("runbook_source"), nullable=False),
        sa.Column("source_company", sa.String(), nullable=True),
        sa.Column(
            "service_tags", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"
        ),
        sa.Column("embedding", Vector(768), nullable=True),
        sa.Column(
            "ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_runbooks_content_hash", "runbooks", ["content_hash"])
    # HNSW index for sub-second cosine similarity search (ESD §15).
    op.execute(
        "CREATE INDEX ix_runbooks_embedding_hnsw ON runbooks "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # --- users ---
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role", _enum("user_role"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # --- audit_log (monthly range-partitioned; ESD §17) ---
    op.execute(
        """
        CREATE TABLE audit_log (
            id uuid NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            actor_type actor_type NOT NULL,
            actor_id text NOT NULL,
            action text NOT NULL,
            target text,
            incident_id uuid,
            metadata jsonb,
            PRIMARY KEY (id, created_at)
        ) PARTITION BY RANGE (created_at)
        """
    )
    op.create_index("ix_audit_log_incident_id", "audit_log", ["incident_id"])
    # Pre-create the rolling retention window of monthly partitions.
    start = _PARTITION_START
    for _ in range(_PARTITION_MONTHS):
        end = _first_of_next_month(start)
        name = f"audit_log_{start.year:04d}_{start.month:02d}"
        op.execute(
            f"CREATE TABLE {name} PARTITION OF audit_log "
            f"FOR VALUES FROM ('{start.isoformat()}') TO ('{end.isoformat()}')"
        )
        start = end


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE")
    op.drop_table("users")
    op.execute("DROP INDEX IF EXISTS ix_runbooks_embedding_hnsw")
    op.drop_table("runbooks")
    op.drop_table("evidence_citations")
    op.drop_table("agent_messages")
    op.drop_table("agent_steps")
    op.drop_table("incident_state_transitions")
    op.drop_table("incidents")
    for name in _ENUMS:
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)
    op.execute("DROP EXTENSION IF EXISTS vector")
